const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.shadowlight,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{"9patch": 0},
	{Sprite2: 0},
	{Platform: 0},
	{Wrap: 0},
	{Sprite3: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{Particles: 0},
	{ShadowLight: 0},
	{ShadowCaster: 0},
	{TiledBackground2: 0},
	{"76y7fh": 0},
	{klklkl8: 0},
	{"9fyf": 0},
	{Text: 0},
	{Button: 0},
	{Text2: 0},
	{Flash: 0},
	{Sprite4: 0},
	{Text3: 0},
	{SpriteFont: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Text4: 0},
	{Button2: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	_76y7fh: class extends self.ITiledBackgroundInstance {},
	klklkl8: class extends self.ITiledBackgroundInstance {},
	_9fyf: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {}
}